import type { AirtableData } from "../components/GameContainer/types";

const data: AirtableData = {
  events: [
    {
      "Start Time": 1,
      Name: "Winter",
      Evil: 6,
      "Expansion Packs": ["Cities and Knights"],
      Funk: 5,
      Description:
        "Ritter müssen mit einem Stroh und einem Schaf aktiviert werden",
      Type: "Until barbarian ship",
      "End Time": 240,
      Icon: "snowflake",
      id: "rec00745OsJ8zqB9P",
    },
    {
      "Start Time": 5,
      Name: "Rückzug",
      Evil: 2,
      "Expansion Packs": ["Cities and Knights"],
      "Enabled (Moderated)": true,
      Funk: 5,
      Description: "Das Barbarenschiff geht drei Felder zurück",
      Type: "One time event",
      "End Time": 180,
      Icon: "hand-point-left",
      id: "rec0OaQWYrgNaK3Fr",
    },
    {
      Set: ["recBcQvteEZZ1wpb9"],
      "Start Time": 10,
      Name: "Reform",
      Evil: 2,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Die SpielerInnen mit den wenigsten Siegpunkten dürfen sich Karten wünschen: Die Anzahl entspricht der Differenz der wenigsten und meisten Siegpunkte.",
      Type: "One time event",
      "End Time": 240,
      Icon: "scale-balanced",
      id: "rec0uy9ozvBguZuqT",
    },
    {
      "Start Time": 1,
      Name: "Räuberbande",
      Evil: 6,
      Funk: 5,
      Description:
        "Wird die 7 gewürfelt, müssen alle SpielerInnen die Hälfte ihrer Karten abgeben",
      Type: "Temporary Event",
      "End Time": 240,
      "Timing Details": "5",
      Icon: "people-robbery",
      id: "rec2UP2Ac7ppsK4po",
    },
    {
      "Start Time": 5,
      Name: "Kreuzzug",
      Evil: 10,
      "Expansion Packs": ["Cities and Knights"],
      Funk: 5,
      Description: "Alle Ritter ziehen los und werden sofort entfernt",
      Type: "One time event",
      "End Time": 240,
      Icon: "chess-knight",
      id: "rec38dqpeWQf1VuW5",
    },
    {
      "Start Time": 1,
      Name: "Teleport",
      Evil: 1,
      Funk: 5,
      Description:
        "Die SpielerIn darf eine entständige Straße an einen anderen, angrenzenden Ort verschieben.",
      Type: "One time event",
      "End Time": 240,
      Icon: "wand-sparkles",
      id: "rec3Ar9882WRIoPvw",
    },
    {
      "Start Time": 1,
      Name: "Rückschritt",
      Evil: 7,
      "Expansion Packs": ["Cities and Knights"],
      Funk: 5,
      Description: "Alle Entwicklungsstufen werden um eins zurückgedreht",
      Type: "One time event",
      "End Time": 240,
      Icon: "rotate-left",
      id: "rec4CqACcIex1gwDs",
    },
    {
      "Start Time": 1,
      Name: "Robin Hood",
      Evil: 1,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Wird eine 7 gewürfelt wird nicht geräubert. Statt dessen darf die jeweilige SpielerIn eine Karte 1 zu 2 tauschen. Der Räuber wird weggestellt",
      Type: "Temporary Event",
      "End Time": 240,
      "Timing Details": "5",
      Icon: "bullseye",
      id: "rec4bseDKhXyUqJHo",
    },
    {
      Set: ["recBcQvteEZZ1wpb9"],
      "Start Time": 1,
      Name: "Dürre",
      Evil: 6,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Getreidefelder geben kein Getreide. Die Zahlenchips werden umgedreht.",
      Type: "Temporary Event",
      "End Time": 240,
      "Timing Details": "5",
      Icon: "sun-plant-wilt",
      id: "rec5wtqpKUsKZJ7fh",
    },
    {
      "Start Time": 1,
      Name: "Komplize",
      Evil: 7,
      Funk: 5,
      Description:
        "Wird eine 7 gewürfelt, dürfen zwei RäuberInnen platziert werden und zwei Karten gezogen werden.",
      Type: "Temporary Event",
      "End Time": 240,
      "Timing Details": "5",
      Icon: "user-group",
      id: "rec7n3n2CNyZ9KB52",
    },
    {
      "Start Time": 1,
      Name: "Schicksal",
      Evil: 8,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Die aktuelle SpielerIn würfelt drei mal. Sie darf ein Ergebnis auswählen und einen Zahlenchip mit der entsprechenden Zahl von der Karte oder aus dem Beutel gegen einen anderen Chip tauschen.",
      Type: "One time event",
      "End Time": 240,
      Icon: "shuffle",
      id: "recD2Lp2kxZBCJxwZ",
    },
    {
      "Start Time": 1,
      Name: "Zweite Chance",
      Evil: 7,
      Funk: 5,
      Description:
        "Jede SpielerIn darf jeweils einfordern, dass nochmal gewürfelt wird.",
      Type: "Temporary Event",
      "End Time": 240,
      "Timing Details": "5",
      Icon: "repeat",
      id: "recDomOEGauirRACz",
    },
    {
      "Start Time": 1,
      Name: "Schätze der Meere",
      Evil: 1,
      "Expansion Packs": ["Seafarers"],
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Alle bebauten Wasserfelder bekommen einen Zahlenchip und sind Oasen.",
      Type: "Temporary Event",
      "End Time": 240,
      "Timing Details": "5",
      Icon: "fish-fins",
      id: "recEhLuWGUqTAi0WW",
    },
    {
      "Start Time": 1,
      Name: "Tumult",
      Evil: 6,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description: "Alle Zahlenchips werden neu verteilt.",
      Type: "One time event",
      "End Time": 240,
      Icon: "cubes-stacked",
      id: "recJtJ3aVptFAORIA",
    },
    {
      "Start Time": 1,
      Name: "Seebeben",
      Evil: 1,
      "Expansion Packs": ["Seafarers"],
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Die SpielerIn, die die meisten Wasserfelder (keine Häfen) besiedelt, kann eins davon gegen ein weißes Feld austauschen.",
      Type: "One time event",
      "End Time": 240,
      Icon: "water",
      id: "recNUnJ7eCeQp3b94",
    },
    {
      "Start Time": 1,
      Name: "Doppelt oder Nichts",
      Evil: 2,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Die SpielerIn darf beliebig viele Karten aus der Hand bestimmen. Danach wird mit 1 Würfel gewürfelt. Bei 1-4 verliert sie die Karten. Bei 5-6 werden sie verdoppelt.",
      Type: "One time event",
      "End Time": 180,
      Icon: "dice",
      id: "recXE5eJI1h0hfkuq",
    },
    {
      Set: ["recBcQvteEZZ1wpb9"],
      "Start Time": 15,
      Name: "Mauerfall",
      Evil: 6,
      "Expansion Packs": ["Cities and Knights"],
      Funk: 5,
      Description: "alle Stadtmauern werden entfernt",
      Type: "One time event",
      "End Time": 240,
      Icon: "lines-leaning",
      id: "recXvBMJPG1wkSHsF",
    },
    {
      "Start Time": 1,
      Name: "Hungersnot",
      Evil: 7,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description: "Es wird nur mit einem Würfel gewürfelt (roter Würfel).",
      Type: "Temporary Event",
      "End Time": 240,
      "Timing Details": "5",
      Icon: "wheat-awn-circle-exclamation",
      id: "recYnqMGrNXtKHw6O",
    },
    {
      "Start Time": 1,
      Name: "Kolonien",
      Evil: 1,
      "Expansion Packs": ["Seafarers"],
      Funk: 5,
      Description:
        "Die SpielerIn, die aktuell am Zug ist, darf so lange Schiffe ab einer Siedlung am Wasser bauen, bis sie neues Land entdeckt. Mit jedem Schiff muss ein neues Feld aufgedeckt werden können",
      Type: "One time event",
      "End Time": 240,
      Icon: "ship",
      id: "recbn6HkXJgnclnSb",
    },
    {
      Set: ["recBEfnWLMQowfI9I"],
      "Start Time": 5,
      Name: "Hinterhalt",
      Evil: 9,
      "Expansion Packs": ["Cities and Knights"],
      "Enabled (Moderated)": true,
      Funk: 5,
      Description: "Das Barbarenschiff greift sofort an.",
      Type: "One time event",
      "End Time": 480,
      Icon: "skull-crossbones",
      id: "recbtaFlBpwgB48AJ",
    },
    {
      Set: ["recBcQvteEZZ1wpb9"],
      "Start Time": 1,
      Name: "Öde",
      Evil: 6,
      "Expansion Packs": ["Cities and Knights"],
      "Enabled (Moderated)": true,
      Funk: 5,
      Description: "Alle Oasen veröden bis zum nächsten Angriff der Barbaren.",
      Type: "Until barbarian ship",
      "End Time": 240,
      Icon: "temperature-full",
      id: "recdYOBpdYlig554r",
    },
    {
      Set: ["recBEfnWLMQowfI9I"],
      "Start Time": 10,
      Name: "Außenposten",
      Evil: 3,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Alle SpielerInnen dürfen für einen Aufpreis von zwei Erz eine Siedlung an einem belieben Ort platzieren",
      Type: "Temporary Event",
      "End Time": 240,
      "Timing Details": "5",
      Icon: "tower-observation",
      id: "receHU1FJlkPDJSRB",
    },
    {
      "Start Time": 1,
      Name: "Verwirrung",
      Evil: 6,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Statt der eigenen Einkünfte von Rohstofffeldern erhält jede SpielerIn, die, der im Uhrzeigersinn nächsten.",
      Type: "Temporary Event",
      "End Time": 240,
      "Timing Details": "5",
      Icon: "group-arrows-rotate",
      id: "recgo4iiknN3c5PGM",
    },
    {
      "Start Time": 1,
      Name: "Faust Gottes",
      Evil: 10,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Die SpielerIn mit den wenigsten Siegpunkten ersetzt eine beliebige Stadt mit ihrer eigenen.",
      Type: "One time event",
      "End Time": 480,
      Icon: "hand-fist",
      id: "reciJd692VJhhiWz2",
    },
    {
      "Start Time": 1,
      Name: "Upside Down",
      Evil: 5,
      "Enabled (Moderated)": true,
      Funk: 8,
      Description: "Als Augenzahl wird die Unterseite der Würfel betrachtet",
      Type: "Temporary Event",
      "End Time": 240,
      "Timing Details": "5",
      Icon: "arrow-down-up-across-line",
      id: "recjiPKq8My9RefvU",
    },
    {
      Set: ["recBcQvteEZZ1wpb9"],
      "Start Time": 1,
      Name: "Erdbeben",
      Evil: 7,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Die SpielerIn darf zwei offene Kacheln miteinander tauschen (außer Wüsten, Wasser und Häfen). Der Zahlenchip bleibt.",
      Type: "One time event",
      "End Time": 240,
      Icon: "house-crack",
      id: "recjrZNuD7xUpmuCb",
    },
    {
      "Start Time": 20,
      Name: "Revolution",
      Evil: 9,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Die SpielerIn mit den meisten Siegpunkten verliert eine beliebige Stadt und wandelt diese  in eine Siedlung um.",
      Type: "One time event",
      "End Time": 480,
      Icon: "house-fire",
      id: "recjyNFxhnmIKXNXg",
    },
    {
      "Start Time": 15,
      Name: "Straßenschaden",
      Evil: 7,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Die SpielerIn mit der längsten Handelsstraße muss drei Straßen entfernen.",
      Type: "One time event",
      "End Time": 240,
      Icon: "road-circle-exclamation",
      id: "reckTbUNX1vZhM2kI",
    },
    {
      "Start Time": 1,
      Name: "Goldgräber",
      Evil: 2,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Die SpielerIn darf eine beliebige Siedlung zu einem unentdeckten Feld umziehen.",
      Type: "One time event",
      "End Time": 240,
      Icon: "hat-cowboy-side",
      id: "recnC1inj5lN4TA8X",
    },
    {
      Set: ["recBEfnWLMQowfI9I"],
      "Start Time": 10,
      Name: "Beförderung",
      Evil: 8,
      "Expansion Packs": ["Cities and Knights"],
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Es wird gewürfelt: Für jeden Ritter wird gewürfelt, ob er auf- oder abgestuft wird: 1-3 abstufen, 4-6 aufstufen. Die Regel für mächtige Ritter greift nicht. Ritter I können nicht abgestuft werden, sondern werden statt dessen entfernt.",
      Type: "One time event",
      "End Time": 240,
      Icon: "medal",
      id: "recpT99PaWfqRJrHY",
    },
    {
      "Start Time": 1,
      Name: "Ressourcenknappheit",
      Evil: 6,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Es wird gewürfelt: Alle Zahlenchips mit dem Ergebnis werden umgedreht",
      Type: "Temporary Event",
      "End Time": 240,
      "Timing Details": "5",
      Icon: "drumstick-bite",
      id: "recrUYhPHJbuXNSVi",
    },
    {
      "Start Time": 1,
      Name: "Vision",
      Evil: 2,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Die SpielerIn, die aktuell am Zug ist, darf eine beliebige Kachel umdrehen",
      Type: "One time event",
      "End Time": 240,
      Icon: "hand-sparkles",
      id: "recsiHVVnt7xtXtyX",
    },
    {
      Set: ["recBEfnWLMQowfI9I"],
      "Start Time": 1,
      Name: "Sozialversicherung",
      Evil: 1,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Alle SpielerInnen, die leer ausgehen, dürfen sich eine Karte ihrer Wahl wünschen.",
      Type: "Temporary Event",
      "End Time": 240,
      "Timing Details": "5",
      Icon: "user-shield",
      id: "recufF94UxxkSi6Nd",
    },
    {
      "Start Time": 10,
      Name: "Flut",
      Evil: 8,
      "Expansion Packs": ["Cities and Knights"],
      Funk: 5,
      Description:
        "Alle Städte und Metropolen an Wasserfeldern (nicht Häfen) ohne Stadtmauer werden zu Siedlungen umgewandelt",
      Type: "One time event",
      "End Time": 240,
      Icon: "house-flood-water",
      id: "recv04scqzIyuOJuC",
    },
    {
      Set: ["recBEfnWLMQowfI9I"],
      "Start Time": 1,
      Name: "Tante Maren",
      Evil: 6,
      "Enabled (Moderated)": true,
      Funk: 5,
      Description:
        "Alle Handkarten werden eingesammelt und gemischt. Im Uhrzeigersinn angefangen von der aktuellen SpielerIn werden die Karten in der Runde verteilt.",
      Type: "One time event",
      "End Time": 240,
      Icon: "star",
      id: "recwi7EUghjTaPSGr",
    },
    {
      "Start Time": 1,
      Name: "Opfer des Waldgottes",
      Evil: 7,
      "Expansion Packs": ["Cities and Knights"],
      Funk: 5,
      Description:
        "Der Waldgott fordert beim Angriff des Barbarenschiffs Holz: Anzahl der SpielerInnen x 2. Kann gemeinsam genügend Holz aufgebracht werden, werden alle SpielerInnen mit zwei Straßen belohnt. Ansonsten wird jeweils eine grüne Entwicklungsstufe zurückgedreht.",
      Type: "Until barbarian ship",
      "End Time": 240,
      Icon: "tree",
      id: "recxHUAHyzt29prYZ",
    },
  ],
  rules: [
    {
      "Enabled [moderated]": true,
      Funk: 5,
      Evil: 1,
      Name: "Metropolen",
      Set: ["recBEfnWLMQowfI9I"],
      Description:
        "Es können Städte zu Metropolen umgerüstet werden: SpielerIn bekommt doppelten Rohstoff und eine Handelsware. Eine Metropole kostet so viel wie eine Stadt. Außerdem geben sie jeweils drei Siegpunkte. Sie benötigen keinen weiteren Ritter.",
      "End Time": 240,
      Icon: "city",
      "Start Time": 20,
      id: "rec4TmOAiJvPo3AUN",
    },
    {
      "Enabled [moderated]": true,
      Funk: 2,
      Evil: 1,
      Name: "Entdecker",
      Description:
        "Das Spielfeld erhält keinen Rahmen. Statt dessen werden ursprünglich 7 Karten aufgedeckt in der Mittel platziert. Neue Karten werden dort angelegt, wo Straßen oder Schiffe hingebaut werden.",
      "End Time": 240,
      Icon: "map",
      "Start Time": 1,
      id: "rec62Mq9l4L024Kbw",
    },
    {
      Funk: 5,
      Evil: 1,
      Name: "Handelskammer",
      Description:
        "Jeder Spieler kann eine Handelskammer bauen, indem er drei Holz und drei Lehm bezahlt. Die Handelskammer funktioniert wie ein Hafen, jedoch darf der Spieler, der die Handelskammer besitzt, den Handel zu einem beliebigen 2:1-Verhältnis durchführen, anstatt sich auf eine bestimmte Ressource festzulegen. Jeder Spieler darf nur eine Handelskammer besitzen.",
      "End Time": 240,
      Icon: "hotel",
      "Start Time": 1,
      id: "rec6eZbCOjrHWTZcz",
    },
    {
      "Enabled [moderated]": true,
      Funk: 5,
      Evil: 1,
      Name: "Stütze",
      Set: ["recBcQvteEZZ1wpb9"],
      Description:
        "Bis 5 Siegpunkte bekommt die würfelnde SpielerIn (außer es wird eine 7 gewürfelt) eine zufällige Karte. Dazu wird ein Zufallskartenstapel zusammengestellt.",
      "End Time": 240,
      Icon: "parachute-box",
      "Start Time": 1,
      id: "recDMAwRyUO0Lz9he",
    },
    {
      "Enabled [moderated]": true,
      Funk: 5,
      Evil: 1,
      Name: "Seidenstraße",
      Set: ["recBcQvteEZZ1wpb9"],
      Description:
        "Die SpielerInnen können sich jederzeit einstimmig auf einen Rohstoff einigen, der von allen 2:1 getauscht werden darf. Zur Kennzeichnung wird eine Karte dieses Rohstoffs zur Seite gelegt.",
      "End Time": 240,
      Icon: "route",
      "Start Time": 1,
      id: "recsJMtX4Fg44dpQz",
    },
  ],
};

export default data;
